name: static-code-tests
on: [pull_request]
jobs:
  static-code-tests:
    runs-on: ubuntu-22.04
    permissions: {}
    container:
      image: quay.io/rhinstaller/kstest-runner
    steps:
      - name: Set up dependencies
        run: |
          pip install pylint==3.1.0 ruff==0.3.7
          
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run static code tests
        run: |
            export PATH="$HOME/.local/bin:$PATH"; ./test/static-code
